const themeData = {
    "newborn": [
        "AVK_9642",
        "WhatsApp Image 2026-06-29 at 11.17.23 AM-3",
        "WhatsApp Image 2026-06-29 at 11.17.23 AM-4"
    ],
    "baby3to6": [
        "WhatsApp Image 2026-06-29 at 11.17.23 AM"
    ],
    "toddlerIndoor": [
        "Astronaut",
        "Baker",
        "Bathtub",
        "Boss Baby",
        "Cakesmash",
        "Candy ",
        "Chef 1",
        "Chef 2",
        "Chef 3",
        "Christmas ",
        "Christmas 2",
        "Cocomelon",
        "Cowboy",
        "Customised 1",
        "Dad'S Little Helper",
        "Doctor ",
        "Farmer",
        "Flight",
        "Flower Jeep",
        "Flower Trolly",
        "Garden bench",
        "Harry Potter",
        "I am One",
        "Jungle theme",
        "Kissing Booth",
        "Krishna",
        "Liabray ",
        "Little soldier",
        "Makeup",
        "Moon",
        "Painter - 2",
        "Painter",
        "Piano 2",
        "Piano",
        "Rock star",
        "Sailor",
        "Sankranthi",
        "Scooty",
        "Shiva 2",
        "Shiva",
        "Traveller 1",
        "Traveller 2",
        "Traveller 3",
        "Treasure Hunt",
        "U bench ",
        "UShape Bench - Honey",
        "UShape Bench - One",
        "UShape Bench Garden",
        "Vintage",
        "Wednesday",
        "Wonder women",
        "Yellow tent"
    ],
    "toddlerOutdoor": [
        "AVK_1130~4.jpg",
        "WhatsApp Image 2026-06-29 at 11.17.23 AM"
    ]
};
